# Generated by Django 3.0.3 on 2023-02-06 15:02

from django.db import migrations, models
import question.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='', verbose_name='Question')),
                ('answer_A', models.CharField(default='', max_length=200, verbose_name='Option A')),
                ('answer_B', models.CharField(default='', max_length=200, verbose_name='Option B')),
                ('answer_C', models.CharField(default='', max_length=200, verbose_name='Option C')),
                ('answer_D', models.CharField(default='', max_length=200, verbose_name='Option D')),
                ('answer_E', models.CharField(default='', max_length=200, verbose_name='Option E')),
                ('answer_F', models.CharField(default='', max_length=200, verbose_name='Option F')),
                ('answer_type', models.CharField(choices=[('1', 'Choice One'), ('2', 'Choice Two'), ('3', 'Choice Three'), ('4', 'Choice Four')], default='1', max_length=1, verbose_name='Answer Type')),
                ('right_answers', question.models.ModifiedArrayField(base_field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1, verbose_name='Correct options'), size=None)),
                ('analysis', models.TextField(default='None for the time being', verbose_name='Subject analysis')),
                ('score', models.PositiveSmallIntegerField(default=2, verbose_name='Score')),
                ('level', models.CharField(choices=[('1', 'Begin'), ('2', 'Simple'), ('3', 'Normal'), ('4', 'Difficult'), ('5', 'Expert')], default='1', max_length=1, verbose_name='Difficulty level')),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choice',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='', verbose_name='Question')),
                ('right_answer', models.CharField(default='', max_length=200, verbose_name='Correct answer')),
                ('analysis', models.TextField(default='None for the time being', verbose_name='Subject analysis')),
                ('score', models.PositiveSmallIntegerField(default=2, verbose_name='Score')),
                ('level', models.CharField(choices=[('1', 'Begin'), ('2', 'Simple'), ('3', 'Normal'), ('4', 'Difficult'), ('5', 'Expert')], default='1', max_length=1, verbose_name='Difficulty level')),
            ],
            options={
                'verbose_name': 'Blank',
                'verbose_name_plural': 'Blank',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='', verbose_name='Question')),
                ('right_answer', models.CharField(choices=[('T', 'Correct'), ('F', 'Wrong')], default='T', max_length=1, verbose_name='Correct answer')),
                ('analysis', models.TextField(default='None for the time being', verbose_name='Subject analysis')),
                ('score', models.PositiveSmallIntegerField(default=2, verbose_name='Score')),
                ('level', models.CharField(choices=[('1', 'Begin'), ('2', 'Simple'), ('3', 'Normal'), ('4', 'Difficult'), ('5', 'Expert')], default='1', max_length=1, verbose_name='Difficulty level')),
            ],
            options={
                'verbose_name': 'True or False',
                'verbose_name_plural': 'True or False',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default='', max_length=200, verbose_name='Question')),
                ('answer_template', models.TextField(default='', verbose_name='Answer template')),
                ('test_case', models.TextField(default='', verbose_name='Test case')),
                ('analysis', models.TextField(default='', verbose_name='Subject analysis')),
                ('score', models.PositiveSmallIntegerField(default=8, verbose_name='Score')),
                ('level', models.CharField(choices=[('1', 'Begin'), ('2', 'Simple'), ('3', 'Normal'), ('4', 'Difficult'), ('5', 'Expert')], default='1', max_length=1, verbose_name='Difficulty level')),
            ],
            options={
                'verbose_name': 'Programming',
                'verbose_name_plural': 'Programming',
                'ordering': ['id'],
            },
        ),
    ]
