# Generated by Django 3.0.3 on 2023-02-06 15:28

from django.db import migrations, models
import question.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='answer_A',
            field=models.TextField(default='', verbose_name='Option A'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='answer_B',
            field=models.TextField(default='', verbose_name='Option B'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='answer_C',
            field=models.TextField(default='', verbose_name='Option C'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='answer_D',
            field=models.TextField(default='', verbose_name='Option D'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='answer_E',
            field=models.TextField(blank=True, default='', verbose_name='Option E'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='answer_F',
            field=models.TextField(blank=True, default='', verbose_name='Option F'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='right_answers',
            field=question.models.ModifiedArrayField(base_field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1, verbose_name='Correct options'), default='A', size=None),
        ),
    ]
