# Generated by Django 3.0.3 on 2023-02-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['id'], 'verbose_name': 'Choice', 'verbose_name_plural': 'Choice'},
        ),
        migrations.AlterModelOptions(
            name='fill',
            options={'ordering': ['id'], 'verbose_name': 'Blank', 'verbose_name_plural': 'Blank'},
        ),
        migrations.AlterModelOptions(
            name='judge',
            options={'ordering': ['id'], 'verbose_name': 'True or False', 'verbose_name_plural': 'True or False'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['id'], 'verbose_name': 'Programming', 'verbose_name_plural': 'Programming'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='analysis',
            field=models.TextField(default='None for the time being', verbose_name='Subject analysis'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='answer_A',
            field=models.CharField(default='', max_length=200, verbose_name='Option A'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='answer_B',
            field=models.CharField(default='', max_length=200, verbose_name='Option B'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='answer_C',
            field=models.CharField(default='', max_length=200, verbose_name='Option C'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='answer_D',
            field=models.CharField(default='', max_length=200, verbose_name='Option D'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='level',
            field=models.CharField(choices=[('1', 'Begin'), ('2', 'Simple'), ('3', 'Normal'), ('4', 'Difficult'), ('5', 'Expert')], default='1', max_length=1, verbose_name='Difficulty level'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.TextField(default='', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='right_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1, verbose_name='Correct option'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='score',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='fill',
            name='analysis',
            field=models.TextField(default='None for the time being', verbose_name='Subject analysis'),
        ),
        migrations.AlterField(
            model_name='fill',
            name='level',
            field=models.CharField(choices=[('1', 'Begin'), ('2', 'Simple'), ('3', 'Normal'), ('4', 'Difficult'), ('5', 'Expert')], default='1', max_length=1, verbose_name='Difficulty level'),
        ),
        migrations.AlterField(
            model_name='fill',
            name='question',
            field=models.TextField(default='', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='fill',
            name='right_answer',
            field=models.CharField(default='', max_length=200, verbose_name='Correct answer'),
        ),
        migrations.AlterField(
            model_name='fill',
            name='score',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='analysis',
            field=models.TextField(default='None for the time being', verbose_name='Subject analysis'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='level',
            field=models.CharField(choices=[('1', 'Begin'), ('2', 'Simple'), ('3', 'Normal'), ('4', 'Difficult'), ('5', 'Expert')], default='1', max_length=1, verbose_name='Difficulty level'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='question',
            field=models.TextField(default='', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='right_answer',
            field=models.CharField(choices=[('T', 'Correct'), ('F', 'Wrong')], default='T', max_length=1, verbose_name='Correct answer'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='score',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='program',
            name='analysis',
            field=models.TextField(default='', verbose_name='Subject analysis'),
        ),
        migrations.AlterField(
            model_name='program',
            name='answer_template',
            field=models.TextField(default='', verbose_name='Answer template'),
        ),
        migrations.AlterField(
            model_name='program',
            name='level',
            field=models.CharField(choices=[('1', 'Begin'), ('2', 'Simple'), ('3', 'Normal'), ('4', 'Difficult'), ('5', 'Expert')], default='1', max_length=1, verbose_name='Difficulty level'),
        ),
        migrations.AlterField(
            model_name='program',
            name='question',
            field=models.TextField(default='', max_length=200, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='program',
            name='score',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='program',
            name='test_case',
            field=models.TextField(default='', verbose_name='Test case'),
        ),
    ]
