# Generated by Django 3.0.3 on 2023-02-06 15:29

from django.db import migrations, models
import question.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20230206_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='right_answers',
            field=question.models.ModifiedArrayField(base_field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1, verbose_name='Correct options'), size=None),
        ),
    ]
