# Generated by Django 4.1.6 on 2023-02-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0004_alter_choice_answer_a_alter_choice_answer_b_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="question",
            field=models.TextField(
                default="Enter your question", verbose_name="Question"
            ),
        ),
    ]
