# Generated by Django 4.1.6 on 2023-02-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0006_alter_choice_answer_a_alter_choice_answer_b_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="question",
            field=models.TextField(
                default="Your company policies require encryption     of sensitive data at rest. You are considering the possible options for protecting data     while storing it at rest on an EBS data volume, attached to an EC2 instance.    Which of these options would allow you to encrypt your data at rest? (Choose three.)",
                verbose_name="Question",
            ),
        ),
    ]
