# Generated by Django 4.1.6 on 2023-02-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Example",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref_id", models.IntegerField()),
                ("content", models.TextField(blank=True, null=True)),
                ("mean", models.TextField(blank=True, null=True)),
                ("trans", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Example",
                "verbose_name_plural": "Example",
                "db_table": "example",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Grammar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("define", models.TextField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("mean", models.TextField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("level", models.CharField(blank=True, max_length=100, null=True)),
                ("favorite", models.BooleanField(default=False)),
                ("remember", models.BooleanField(default=False)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Grammar",
                "verbose_name_plural": "Grammar",
                "db_table": "grammar",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="JaVi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(blank=True, max_length=255, null=True)),
                ("phonetic", models.CharField(blank=True, max_length=255, null=True)),
                ("mean", models.TextField(blank=True, null=True)),
                ("seq", models.SmallIntegerField(blank=True, null=True)),
                ("opposite", models.CharField(blank=True, max_length=255, null=True)),
                ("favorite", models.BooleanField(default=False)),
                ("synsets", models.CharField(blank=True, max_length=255, null=True)),
                ("related", models.TextField(blank=True, null=True)),
                (
                    "pronunciation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Japanese - Vietnamese",
                "verbose_name_plural": "Japanese - Vietnamese",
                "db_table": "javi",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Kanji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kanji", models.CharField(max_length=10)),
                ("mean", models.CharField(blank=True, max_length=150, null=True)),
                ("level", models.SmallIntegerField(blank=True, null=True)),
                ("on", models.CharField(blank=True, max_length=200, null=True)),
                ("kun", models.CharField(blank=True, max_length=200, null=True)),
                ("svg", models.TextField(blank=True, null=True)),
                ("detail", models.TextField(blank=True, null=True)),
                ("short", models.CharField(blank=True, max_length=10, null=True)),
                ("frequenty", models.IntegerField(blank=True, null=True)),
                ("components", models.TextField(blank=True, null=True)),
                ("stroke_count", models.SmallIntegerField(default=-1)),
                ("components_detail", models.TextField(blank=True, null=True)),
                ("examples", models.TextField(blank=True, null=True)),
                ("favorite", models.BooleanField(default=False)),
                ("remember", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Kanji",
                "verbose_name_plural": "Kanji",
                "db_table": "kanji",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ViJa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=255)),
                ("kind", models.CharField(blank=True, max_length=255, null=True)),
                ("mean", models.TextField(blank=True, null=True)),
                ("favorite", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Vietnamese - Japanese",
                "verbose_name_plural": "Vietnamese - Japanese",
                "db_table": "vija",
                "ordering": ["id"],
            },
        ),
    ]
