# Generated by Django 3.0.3 on 2023-02-05 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_auto_20230204_1437'),
        ('user', '0009_auto_20230205_0537'),
        ('question', '0002_auto_20230205_0537'),
        ('record', '0004_auto_20200425_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choicerecord',
            options={'ordering': ['id'], 'verbose_name': 'Selected Questions Answer Record', 'verbose_name_plural': 'Selected Questions Answer Record'},
        ),
        migrations.AlterModelOptions(
            name='fillrecord',
            options={'ordering': ['id'], 'verbose_name': 'Fill in the blank questions and answer records', 'verbose_name_plural': 'Fill in the blank questions and answer records'},
        ),
        migrations.AlterModelOptions(
            name='judgerecord',
            options={'ordering': ['id'], 'verbose_name': 'Judgment question answer record', 'verbose_name_plural': 'Judgment question answer record'},
        ),
        migrations.AlterModelOptions(
            name='programrecord',
            options={'ordering': ['id'], 'verbose_name': 'Programming Questions Answer Record', 'verbose_name_plural': 'Programming Questions Answer Record'},
        ),
        migrations.AlterField(
            model_name='choicerecord',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Choice', verbose_name='Choice'),
        ),
        migrations.AlterField(
            model_name='choicerecord',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Practice', verbose_name='Practise'),
        ),
        migrations.AlterField(
            model_name='choicerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='choicerecord',
            name='your_answer',
            field=models.TextField(blank=True, null=True, verbose_name='Your answer'),
        ),
        migrations.AlterField(
            model_name='fillrecord',
            name='fill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Fill', verbose_name='Blank'),
        ),
        migrations.AlterField(
            model_name='fillrecord',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Practice', verbose_name='Practise'),
        ),
        migrations.AlterField(
            model_name='fillrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='fillrecord',
            name='your_answer',
            field=models.TextField(blank=True, null=True, verbose_name='Your answer'),
        ),
        migrations.AlterField(
            model_name='judgerecord',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Judge', verbose_name='True or False'),
        ),
        migrations.AlterField(
            model_name='judgerecord',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Practice', verbose_name='Practise'),
        ),
        migrations.AlterField(
            model_name='judgerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='judgerecord',
            name='your_answer',
            field=models.TextField(blank=True, null=True, verbose_name='Your answer'),
        ),
        migrations.AlterField(
            model_name='programrecord',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Practice', verbose_name='Practise'),
        ),
        migrations.AlterField(
            model_name='programrecord',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Program', verbose_name='Programming'),
        ),
        migrations.AlterField(
            model_name='programrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='programrecord',
            name='your_answer',
            field=models.TextField(blank=True, null=True, verbose_name='Your answer'),
        ),
    ]
