# Generated by Django 4.1.6 on 2023-02-12 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=20, verbose_name="Test name"
                    ),
                ),
                ("exam_date", models.DateField(default="", verbose_name="Test date")),
                (
                    "total_time",
                    models.PositiveSmallIntegerField(
                        default=120,
                        help_text="Press the length and fill in the minute",
                        verbose_name="duration",
                    ),
                ),
                (
                    "major",
                    models.CharField(default="", max_length=20, verbose_name="major"),
                ),
                (
                    "tips",
                    models.TextField(default="", verbose_name="Candidates' notes"),
                ),
                (
                    "clazzs",
                    models.ManyToManyField(
                        to="user.clazz", verbose_name="Class to take the exam"
                    ),
                ),
            ],
            options={
                "verbose_name": "take an exam",
                "verbose_name_plural": "take an exam",
                "db_table": "exam_info",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=20, verbose_name="Test paper name"
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Total score"
                    ),
                ),
                (
                    "choice_number",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="Number of choice questions"
                    ),
                ),
                (
                    "fill_number",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="Number of filling questions"
                    ),
                ),
                (
                    "judge_number",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="Number of judgments"
                    ),
                ),
                (
                    "program_number",
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name="Number of programming questions"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("1", "Begin"),
                            ("2", "Simple"),
                            ("3", "Normal"),
                            ("4", "Difficult"),
                            ("5", "Expert"),
                        ],
                        default="1",
                        max_length=1,
                        verbose_name="Difficulty level",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test papers ",
                "verbose_name_plural": "Test papers ",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Practice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, verbose_name="Practice nametice name"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Practice time"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.student",
                        verbose_name="student",
                    ),
                ),
            ],
            options={
                "verbose_name": "practise",
                "verbose_name_plural": "practise",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default="", verbose_name="Fraction"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="Modify"),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exam.exam",
                        verbose_name="take an exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.student",
                        verbose_name="student",
                    ),
                ),
            ],
            options={
                "verbose_name": "score",
                "verbose_name_plural": "score",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="paper",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="exam.paper",
                verbose_name="Test paper",
            ),
        ),
    ]
