# Generated by Django 3.0.3 on 2023-02-04 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20230204_1437'),
        ('exam', '0010_auto_20200425_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['id'], 'verbose_name': 'take an exam', 'verbose_name_plural': 'take an exam'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['id'], 'verbose_name': 'score', 'verbose_name_plural': 'score'},
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['id'], 'verbose_name': 'Test papers ', 'verbose_name_plural': 'Test papers '},
        ),
        migrations.AlterModelOptions(
            name='practice',
            options={'ordering': ['id'], 'verbose_name': 'practise', 'verbose_name_plural': 'practise'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='clazzs',
            field=models.ManyToManyField(to='user.Clazz', verbose_name='Class to take the exam'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(default='', verbose_name='Test date'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='major',
            field=models.CharField(default='', max_length=20, verbose_name='major'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='Test name'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='paper',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='exam.Paper', verbose_name='Test paper'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='tips',
            field=models.TextField(default='', verbose_name="Candidates' notes"),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_time',
            field=models.PositiveSmallIntegerField(default=120, help_text='Press the length and fill in the minute', verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Exam', verbose_name='take an exam'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.PositiveSmallIntegerField(default='', verbose_name='Fraction'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student', verbose_name='student'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Modify'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='choice_number',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Number of choice questions'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='fill_number',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Number of filling questions'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='judge_number',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Number of judgments'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='level',
            field=models.CharField(choices=[('1', 'getting Started'), ('2', 'Simple'), ('3', 'usually'), ('4', 'More difficult'), ('5', 'difficulty')], default='1', max_length=1, verbose_name='Difficulty level'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='Test paper name'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='program_number',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Number of programming questions'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='score',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Total score'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Practice time'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Practice nametice name'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student', verbose_name='student'),
        ),
    ]
