# Generated by Django 4.1.6 on 2023-02-12 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clazz",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=20, verbose_name="grade")),
                ("major", models.CharField(max_length=20, verbose_name="major")),
                ("clazz", models.CharField(max_length=20, verbose_name="class")),
            ],
            options={
                "verbose_name": "class",
                "verbose_name_plural": "class",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=20, verbose_name="Name"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("m", "male"), ("f", "female")],
                        default="male",
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("Lecturer", "Lecturer"),
                            ("Associate Professor", "Associate Professor"),
                            ("Professor", "Professor"),
                        ],
                        default="lecturer",
                        max_length=20,
                        verbose_name="Job Title",
                    ),
                ),
                (
                    "institute",
                    models.CharField(default="", max_length=20, verbose_name="College"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "teacher",
                "verbose_name_plural": "teacher",
                "db_table": "user_teacher",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=20, verbose_name="Name"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("m", "Male"), ("f", "Female")],
                        default="",
                        max_length=1,
                        verbose_name="gender",
                    ),
                ),
                (
                    "clazz",
                    models.ForeignKey(
                        default="1",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.clazz",
                        verbose_name="class",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "student",
                "verbose_name_plural": "student",
                "db_table": "user_student",
                "ordering": ["id"],
            },
        ),
    ]
