# Generated by Django 3.0.3 on 2023-02-05 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_auto_20230204_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clazz',
            options={'ordering': ['id'], 'verbose_name': 'class', 'verbose_name_plural': 'class'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id'], 'verbose_name': 'student', 'verbose_name_plural': 'student'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['id'], 'verbose_name': 'teacher', 'verbose_name_plural': 'teacher'},
        ),
        migrations.AlterField(
            model_name='clazz',
            name='clazz',
            field=models.CharField(max_length=20, verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='clazz',
            name='major',
            field=models.CharField(max_length=20, verbose_name='major'),
        ),
        migrations.AlterField(
            model_name='clazz',
            name='year',
            field=models.CharField(max_length=20, verbose_name='grade'),
        ),
        migrations.AlterField(
            model_name='student',
            name='clazz',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='user.Clazz', verbose_name='class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='', max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='male', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='institute',
            field=models.CharField(default='', max_length=20, verbose_name='College'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='title',
            field=models.CharField(choices=[('Lecturer', 'Lecturer'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor')], default='lecturer', max_length=20, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
